### PR TITLE
Add rfc8226

### PR DESCRIPTION
**Pull request by russhousley**

### CODE REVIEW

**Comment by etingof** [comment]
It seems like this PR is exactly the same as #21, is not it? I wonder why GitHub still shows differences against master given that these changes may be there already...

So is it an accidental duplicate PR?

**Comment by russhousley** [comment]
I thought I was adding a new module and the associated test.

**Comment by russhousley** [comment]
I just added rfc4055.py and the associated test file.  Can you pick them up as part of this PR, or do you want a separate one?

**Comment by etingof** [comment]
Thank you!

**Pull request merged**
