### PR TITLE
Add support for RFC 5035

### PR DESCRIPTION
**Pull request by russhousley**
Add module and test for RFC 5035.

### CODE REVIEW

**Comment by etingof** [comment]
Hey, thank you for pushing this! Would you take a look why the CI tests are failing please?

```

Obtaining file:///home/travis/build/etingof/pyasn1-modules
Requirement already satisfied (use --upgrade to upgrade): pyasn1<0.5.0,>=0.4.1 in /home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages (from pyasn1-modules==0.2.6)
Installing collected packages: pyasn1-modules
  Running setup.py develop for pyasn1-modules
Successfully installed pyasn1-modules
0.42s$ PYTHONPATH=.:$PYTHONPATH python tests/__main__.py
Traceback (most recent call last):
  File "tests/__main__.py", line 51, in <module>
    'tests.test_rfc8619.suite']
  File "/opt/python/3.2.6/lib/python3.2/unittest/loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.2.6/lib/python3.2/unittest/loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.2.6/lib/python3.2/unittest/loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/travis/build/etingof/pyasn1-modules/tests/test_rfc5035.py", line 16, in <module>
    from pyasn1_modules import rfc5035
  File "/home/travis/build/etingof/pyasn1-modules/pyasn1_modules/rfc5035.py", line 39, in <module>
    sha256AlgId['parameters'] = None
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/univ.py", line 2069, in __setitem__
    self.setComponentByName(idx, value)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/univ.py", line 2207, in setComponentByName
    idx, value, verifyConstraints, matchTags, matchConstraints
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/univ.py", line 2361, in setComponentByPosition
    value = subComponentType.clone(value=value)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/base.py", line 349, in clone
    return self.__class__(value, **initializers)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/univ.py", line 819, in __init__
    base.AbstractSimpleAsn1Item.__init__(self, value, **kwargs)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/base.py", line 240, in __init__
    value = self.prettyIn(value)
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pyasn1/type/univ.py", line 878, in prettyIn
    return bytes(value)
TypeError: 'NoneType' object is not iterable
```

**Comment by russhousley** [comment]
These tests work fine on my machine.  Could you still have the rfc5035.py from our debug session installed?

Russ

**Comment by etingof** [comment]
That is [CI failure](https://travis-ci.org/etingof/pyasn1-modules/builds/546913278?utm_source=github_status&utm_medium=notification), it runs against your PR as it is.

**Comment by russhousley** [comment]
I see,  It appears that assignng the parameters to None works fine in python2, but in python3 it tries to iterate over the None.  I will try to investigate further.

**Comment by russhousley** [comment]
Does this seem like a good way forward?

sha256AlgId = rfc5280.AlgorithmIdentifier()
sha256AlgId['algorithm'] = univ.ObjectIdentifier('2.16.840.1.101.3.4.2.1')
if sys.version_info[0] < 3:
    sha256AlgId['parameters'] = None

**Pull request closed without merging**
