### PR TITLE
Add support for RFC 5751

### PR DESCRIPTION
**Pull request by russhousley**
Add module and test for RFC 5751

### CODE REVIEW

**Comment by etingof** [comment]
Hey, looks like a simple bug pops up in the CI:

```
======================================================================
616ERROR: testDerCodec (tests.test_rfc5751.SignedMessageTestCase)
617----------------------------------------------------------------------
618Traceback (most recent call last):
619  File "/home/travis/build/etingof/pyasn1-modules/tests/test_rfc5751.py", line 76, in testDerCodec
620    substrate = pem.readBase64fromText(pem_text)
621NameError: global name 'pem_text' is not defined
622
623
```

**Comment by etingof** [comment]
I've fixed that simple bug, now re-encoding seems to fail:

```
======================================================================
613FAIL: testDerCodec (tests.test_rfc5751.SignedMessageTestCase)
614----------------------------------------------------------------------
615Traceback (most recent call last):
616  File "/home/travis/build/etingof/pyasn1-modules/tests/test_rfc5751.py", line 82, in testDerCodec
617    assert der_encode(asn1Object) == substrate
618AssertionError
619
620
```

**Comment by russhousley** [comment]
There are two problems.  First, there is a missing "self.".  That is trivial to fix.  Second, this module and rfc2985.py both include definitions of the SMIMECapabilities attribute.  The two definitions are using a different string ('capabilityID' vs 'algorithm') with openTypes.  I need to do some investigation to figure out the best way to resolve this one.

**Comment by etingof** [comment]
> First, there is a missing "self.". That is trivial to fix

I think I've fixed that in your master.

**Comment by russhousley** [comment]
I just pushed the fixed files.  It also required a small change to rfc2985.py to make everything consistent.  There is a long comment in the code about why this was needed.

**Comment by etingof** [comment]
Thank you!

**Pull request merged**
