### PR TITLE
Add support for RFC 7894

### PR DESCRIPTION
**Pull request by russhousley**
Add module and test for RFC 7894

### CODE REVIEW

**Comment by etingof** [comment]
There seems to be one failure in unit tests:

```
======================================================================
ERROR: testOpenTypes (tests.test_rfc7894.CertBundleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/etingof/pyasn1-modules/tests/test_rfc7894.py", line 65, in testOpenTypes
    decodeOpenTypes=True)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 1553, in __call__
    **options
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 609, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 1553, in __call__
    **options
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 609, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 1553, in __call__
    **options
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 712, in valueDecoder
    component, head = decodeFun(head, componentType, **options)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 1553, in __call__
    **options
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 684, in valueDecoder
    asn1Spec=openType, **options
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pyasn1/codec/ber/decoder.py", line 1587, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
PyAsn1Error: <TagSet object, tags 0:32:16> not in asn1Spec: <ObjectIdentifier schema object, tagSet <TagSet object, tags 0:0:6>>
```
Could you please take a look?

Thank you!

**Comment by russhousley** [comment]
The decode without decodeOpenTypes=True works under py2 and py3.
The decode with decodeOpenTypes=True works under py2, but it fails under py3.

I do not see anything in the module or the test routine to cause this situation.

**Comment by etingof** [comment]
@russhousley Did you close this PR on purpose?

**Comment by russhousley** [comment]
I cannot figure out what was going on with the error on the py3 test, and I wanted to get the other two modules out.

Russ

**Comment by etingof** [comment]
But now the change is gone, do you still have it somewhere?

One way of working on multiple changes in parallel would be to have each in its own branch rather than all of them in master.

**Pull request closed without merging**
