### PR TITLE
Add support for RFC 7508

### PR DESCRIPTION
**Pull request by russhousley**
Add module and test for RFC 7508.  Note that the module depends on the recent changes to pyasn1 around constraint.PermittedAlphabetConstraint, so when this is merged into master the requirements.txt should also be updated.

### CODE REVIEW

**Comment by etingof** [comment]
Ah, you seem to have closed this PR... Is it for a reason or accidentally?

**Comment by russhousley** [comment]
No, I did not mean to close it.  Let me know if I need to make a new PR.

**Comment by etingof** [comment]
> No, I did not mean to close it. Let me know if I need to make a new PR.

No, this one is good!

**Comment by etingof** [comment]
But may be you need to rebase it? The files in this PR do not seemingly relate to RFC 7508.

**Comment by russhousley** [comment]
I figured out what I did to mess it up, but I'm not 100% sure I properly fixed it.  That said, the files are there:

https://github.com/russhousley/pyasn1-modules/blob/master/pyasn1_modules/rfc7508.py

https://github.com/russhousley/pyasn1-modules/blob/master/tests/test_rfc7508.py

**Comment by etingof** [comment]
> I figured out what I did to mess it up, but I'm not 100% sure I properly fixed it. That said, the files are there:
> 
> https://github.com/russhousley/pyasn1-modules/blob/master/pyasn1_modules/rfc7508.py
> 
> https://github.com/russhousley/pyasn1-modules/blob/master/tests/test_rfc7508.py

#102 should have done it!

**Pull request closed without merging**
