### PR TITLE
Added maps for use with openType

### PR DESCRIPTION
**Pull request by russhousley**
Added maps for use with openType to RFC 2634, RFC 3274, RFC 3709, RFC 3779, RFC 4073, RFC 4108, RFC 4108, RFC 5035, RFC 5083, RFC 5940, RFC 5958, RFC 6010, RFC 6019, RFC 6402, RFC 7191, RFC 8226, and RFC 8520

### CODE REVIEW

**Comment by etingof** [comment]
Looks like something is not quite right:

```
NameError: name 'KeyPackage' is not defined
```

**Comment by russhousley** [comment]
I do not know why running tests on my system did not detect this error.  The line should be:

AsymmetricKeyPackage.subtypeSpec=constraint.ValueSizeConstraint(1, MAX)

**Comment by etingof** [comment]
Well, it is actually `KeyPackage` in the PR. I just fixed that, let's see...

**Comment by etingof** [comment]
Next problem is this:

```

Traceback (most recent call last):
  File "tests/__main__.py", line 51, in <module>
    'tests.test_rfc8619.suite']
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 613, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 584, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_rfc5958
```

**Comment by etingof** [comment]
Now all tests pass with the latest pyasn1. CI still uses older (released) version, that's why CI still fails.

Perhaps it's time for a new release!

**Comment by russhousley** [comment]
I see what happened.  I originally had some code that used RFC 6031 in the test.  I rewrote it because the module for RFC 6031 is not ready for release yet, but of course, it is still on my system.  The import of that module needs to be removed.

**Comment by russhousley** [comment]
Yes, the openTypes depend on the yet to be released pyasn1.

**Comment by etingof** [comment]
With direct dependency on GitHub repo, it's only a matter of Python 3.2-3.3:

```
  File "tests/__main__.py", line 51, in <module>
    'tests.test_rfc8619.suite']
  File "/opt/python/3.2.6/lib/python3.2/unittest/loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.2.6/lib/python3.2/unittest/loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/3.2.6/lib/python3.2/unittest/loader.py", line 105, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_rfc2314'
```

**Comment by etingof** [comment]
I can't understand the above mentioned failure. It may have something to do with importing machinery... I suppose it's irrelevant to your patch.

**Pull request merged**
